project:
  type: website
  output-dir: docs
  
website:
  title: "Jason D. Carlisle"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - teaching.qmd

format:
  html:
    theme: cosmo
    toc: true