---
title: "About"
---

## Employment

-   2022 - present. Quantitative Biologist. Wyoming Game and Fish Department, Wildlife Division, Science, Research, and Analytical Support Unit. Laramie, WY.

-   2017 - 2022. Research Biometrician, Consulting Statistician, and Project Manager. Western EcoSystems Technology, Inc. (WEST). Laramie, WY.

-   2011 - 2017. Graduate Assistant (Research, Teaching, and Curatorial). University of Wyoming, Department of Zoology and Physiology. Laramie, WY.

-   2011 - 2011. Research Associate. Brigham Young University, Department of Plant and Wildlife Sciences. Provo, UT.

-   2010 - 2010. Wildlife Technician. Utah Division of Wildlife Resources, Statewide Riparian Monitoring Program. Salt Lake City, UT.

-   2009 - 2009. Wildlife Technician. Utah Division of Wildlife Resources, Utah Lake Wetland Preserve. Springville, UT.

-   2005 - 2005. Wildlife Technician. Utah Division of Wildlife Resources, Central Region Wildlife Section. Springville, UT.

## Education

-   PhD, Ecology, minor in Statistics. 2017. University of Wyoming, Department of Zoology & Physiology, Program in Ecology, Wyoming Cooperative Fish & Wildlife Research Unit.

-   BS, Wildlife Science, minor in Geographic Information Science. 2011. Utah State University, Department of Wildland Resources, College of Natural Resources.

## Professional Affiliations

-   The Wildlife Society
    -   Wyoming Chapter
    -   Central Mountains and Plains Section
    -   Biometrics Working Group
-   Wyoming Golden Eagle Working Group
-   American Ornithological Society (former)
-   The Society for Marine Mammalogy (former)
